# -*- coding: utf-8 -*-
"""Salinan Capstone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eeWHZM-sziHgsuicg9-5hcxCaoyh9kmw

## **Data Understanding**

**Import Library**
"""

#melakukan import library
import streamlit as st
import numpy as np
import pandas as pd

"""**Meload dataste dari github**"""

# load dataset
url = 'https://raw.githubusercontent.com/muhamadilyas17/capstone/main/water_potability.csv'
kualitas_air = pd.read_csv(url)
kualitas_air

def welcome():
  return 'welcome all'

def prediction(ph1):
  ph = [0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  if ph1>=0 and ph<1:
    ph[0]=1
  elif ph1>=1 and ph<2:
    ph[1]=1
  elif ph1>=2 and ph<3:
    ph[2]=1
  elif ph1>=3 and ph<4:
    ph[3]=1
  elif ph1>=4 and ph<5:
    ph[4]=1
  elif ph1>=5 and ph<6:
    ph[5]=1
  elif ph1>=6 and ph<7:
    ph[6]=1
  elif ph1>=7 and ph<8:
    ph[7]=1
  elif ph1>=8 and ph<9:
    ph[8]=1
  elif ph1>=9 and ph<10:
    ph[9]=1
  elif ph1>=10 and ph<11:
    ph[10]=1
  elif ph>=11 and ph<12:
    ph[11]=1
  elif ph1>=12 and ph<13:
    ph[12]=1
  elif ph1>=13 and ph<14:
    ph[13]=1
  else:
    ph[14]=1


  prediction = classifier.predict([[ph[0],ph[1],ph[2],ph[3],ph[4],ph[5],ph[6],ph[7],ph[8],ph[9],ph[10],ph[11],ph[12],ph[13],ph[14]]])
  
  return prediction

def main():
  st.title("Water Prediction App")
  html_temp=""
  ans=0
  st.markdown(html_temp,unsafe_allow_html=True)
  get_ph = st.slider("Water PH ?", value=25)

if st.button("Predict"):
  ans=prediction(get_ph)[0]
  if ans==0:
    st.success('Air Sehat')
  else:
    st.success('Air Berpolusi')

if __name__=='__main__':
  main()